---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: juno-mainnet-cert
spec:
  secretName: juno-mainnet-tls

  dnsNames:
    - juno.mainnet.iosis.tech
  issuerRef:
    name: letsencrypt-http01
    kind: Issuer