---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: juno-sepolia-cert
spec:
  secretName: juno-sepolia-tls

  dnsNames:
    - juno.sepolia.iosis.tech
  issuerRef:
    name: letsencrypt-http01
    kind: Issuer